### ISSUE TITLE
Create chocolatey package

### ISSUE THREAD

**Issue by sebescudie** [sebescudie/GammaLauncher#12]

**Comment by digitalcoyote** [comment]
If you need assistance, I maintain ~35 packages using an AU repo (watches repositories for releases and packs/publishes automatically). I'd be happy to answer any questions regarding the process.

**Comment by mhusinsky** [comment]
i'd be very happy about a choco or winget package as it would make the install process on multiple computers (e.g. student lab) much easier.

**Comment by sebescudie** [comment]
Yep, this is also something I'd love to have, just did not find the motivation yet :-)

Next release (which should land soon) will have an installer which should already make deployment a bit easier, but the Choco/winget thing will be tackled right after.
