### ISSUE TITLE
vvvv enumeration

### ISSUE THREAD

**Issue by sebllll** [sebescudie/GammaLauncher#14]
![image](https://user-images.githubusercontent.com/646501/96420926-693a7d80-11f6-11eb-8122-d792e02f7c4d.png)
hi sebes,

first of all thanks for this great everyday helper!

But i have two little issues:

1. vvvv beta is also enumerated in the dropdown, which is cool, but its string isn't drawn (the first two entries in my screenshot)
2. i need more than 8 entries in the dropdown :)

**Comment by sebescudie** [comment]
Hey there!

1. Eh, nice catch! I keep beta and gamma installed in their default location, did not expect betas it in Program Files! At the moment, the launcher is not meant to work with beta, so I'll simply discard beta versions for now. I'll try to add beta support in a future version of the launcher.
2. And... yeah, I see :) In such cases I guess the dropdown is not the ideal UI solution. Maybe the new DropdownGrid widget in Elementa will do the trick.

I'll try to fix those tomorrow, thanks for reporting!

**Comment by sebescudie** [comment]
Newest launcher (3.3.0) fixes those issues :

- Beta versions are discarded
- Dropdown menu can reacts to scrollwheel when hovered
