### ISSUE TITLE
No new previews found because branch has changed

### ISSUE THREAD

**Issue by tebjan** [sebescudie/GammaLauncher#23]
This needs an update of the TeamCity branch to look at.

**Comment by sebescudie** [comment]
Thanks for the report, I'll have a look tomo morning.

**Comment by sebescudie** [comment]
This is weird, when I query available branches with `https://teamcity.vvvv.org/guestAuth/app/rest/projects/vvvv_gamma/branches`, I get this :

```xml
<branches count="2">
    <branch name="<default>" default="true"/>
    <branch name="preview/2021.4.0"/>
</branches>
```

`<default>` should rather be `preview/2021.4`, not sure why it's named that way.
