### ISSUE TITLE
Long load time on first startup

### ISSUE THREAD

**Issue by tgd-git** [sebescudie/GammaLauncher#30]
the current launcher 4.1.0 takes a very long time on first startup.

**Comment by sebescudie** [comment]
Hey, thanks for the report. I don't remember seeing the app taking too long to start on first use (tested just now with latest 4.1.1). Does the issue still occur with this one? If so, could you explicit how long is "very long"?

Thanks!

**Comment by tgd-git** [comment]
it was about 10 sec and just the first start after boot. seen on two different machines . the new one seems fine again.

**Comment by sebescudie** [comment]
Hey, closing this one, feel free to re-open if you witness long startup times.
