### ISSUE TITLE
Clean old folders in install directory

### ISSUE THREAD

**Issue by tebjan** [sebescudie/GammaLauncher#34]
Uninstalling vvvv leaves a folder there, if one is sure that nothing was changed manually in a vvvv install folder, one could press a button to move those directories into the bin.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/1094716/158801220-d3c8dd85-de0f-4e4c-a288-b41fe4f8748a.png">

**Comment by sebescudie** [comment]
Hey, yes noticed that as well, I could actually delete this folder when the uninstaller successfully exits, but shouldn't/couldn't it be taken care of by the uninstaller?

**Comment by tebjan** [comment]
This might be the first thought, of course. But the installer is only allowed to remove files that it put there itself. We don't know what a user did or whether some files are changed, so we cannot just deleted this folder as it could potentially destroy user work.

so the cleanup has to be an active user decision, which is better placed in the launcher. also, the installer would only be allowed to manage its own specific version, but in this case one just wants to clean all.

**Comment by sebescudie** [comment]
This feature will be part of the next release!

There is a quirk though. It looks like the Launcher has to run in elevated mode to delete files in `Program Files`, which makes sense. 

But apparently, a non-elevated program cannot send messages (like a drag and drop action) to an elevated one. Windows Explorer is usually not elevated, which means that the feature that allows to open a document by dropping it on the Launcher will not work in elevated mode.
