### ISSUE TITLE
Sorting of versions is wrong

### ISSUE THREAD

**Issue by seltzdesign** [sebescudie/GammaLauncher#37]
The sorting of the dropdown of versions is wrong. It is not interpreting the numbers correctly, but doing a pure alphabetical sort. "2021.4.10-138" should come between "2022.5.0-0040" and "2021.4.9-975". But now it is between "2022.4.2" and "2022.4.1".

Thanks for fixing, GammaLauncher rules.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/6575829/179927570-38f15526-aeda-4fce-a435-d7f5e5802a43.png">

**Comment by seltzdesign** [comment]
I just noticed another issue, which you can see in the same screenshot: The dropdown with the versions actually gets cut off. It either needs to be scrollable or extend outside of the frame of the application. Thanks!

**Comment by sebescudie** [comment]
Wow, for whatever reason I'm only seeing this issue now, sorry for the delay! Yes, that looks fishy indeed. I'm relying on some .NET library to parse semver, and it indeed seems to have issues sorting those. Thanks for the report, cannot promise when but I'll try to have a look these days.

Regarding your second issue, there's no scrollable dropdown in Elementa and I don't see one being added in the near feature. Not ideal but you can already scroll while hovering the (closed) dropdown to scroll through versions.
This issue will most likely be solved when rewriting the launcher using ImGUI, see #40

**Comment by sebescudie** [comment]
@seltzdesign This will be fixed in next release, thanks again for the report.
