### ISSUE TITLE
Refresh available versions

### ISSUE THREAD

**Issue by sunep** [sebescudie/GammaLauncher#39]
It would be cool to have a refresh button that gets the available versions.

## two examples
- When for some reason you start your GammaLauncher before your machine is online. then you need to restart GL for it to fetch a new list.
- Waiting for a new preview that will be ready at a moments notice

**Comment by sebescudie** [comment]
Hey sune, CTRL + R should already do that. But I agree a button in the UI could make more sense!

**Comment by sebescudie** [comment]
Just added that to the README. When GammaLauncher switches to ImGUI, this will be doable by clicking a button. Thanks for the suggestion!
