### ISSUE TITLE
Upcoming Major Download

### ISSUE THREAD

**Issue by sunep** [sebescudie/GammaLauncher#41]
It would be nice if Gammalauncher could include all the options for download. Currently it would be 2021.4 and 2022.5 as the upcoming major.
Having gotte used to the convenience of gammalauncher, it feels clumsy to download from visualprogramming.net

**Comment by sebescudie** [comment]
Hey again,

This will also be fixed in the next release : 2022.5 builds are now showing up in the Launcher.
