### ISSUE TITLE
Drag dropping a .vl file with allow multiple disabled, says you need to drop the file on an instance of gamma, even though no instance is running

### ISSUE THREAD

**Issue by sunep** [sebescudie/GammaLauncher#42]
it would be practical if it could launch this way

**Comment by sebescudie** [comment]
Hey, 

Sorry for the late answer, and thanks for the feedback. That behavior was indeed nonsensical.

This was just fixed and will be available in the next version : if the user has not selected `Allow Multiple`, the launcher will append this argument when dropping a `.vl` file.

**Comment by sunep** [comment]
Not sure if I understand it correctly, but I think the expected behavior when Allow multiple is not enabled, would be to launch it in the already running instance

**Comment by sebescudie** [comment]
For that the launcher's process would have to somehow give orders to the running vvvv process, which is not something I expect to be doable in a clean an sustainable way.

But then, what if you already have multiple instances running? How would the launcher know which one you're targetting?

If you want to open a `.vl` document in an instance that's already running, you can just drop that document on the patch editor of that instance.

**Comment by sunep** [comment]
would it be possible to have something like a pop up telling you that you need to drop the file on the instance on which you want the file to be opened if you want it in the same instance. and then have the option to close the dialog or open in a new instance. I would not expect gammalauncher to open a new instance straight away if allow multiple is unticked.
