### ISSUE TITLE
ShowSettingsLocation uses a lot of performance for what it does.

### ISSUE THREAD

**Issue by bj-rn** [sebescudie/GammaLauncher#45]
Nothing major but also an easy fix.

![image](https://user-images.githubusercontent.com/1632591/217258968-9e3bb576-158f-48d0-a59d-10d2c91eb463.png)

before:
![image](https://user-images.githubusercontent.com/1632591/217258711-5e993a2f-c5f5-490c-a591-88a25b8d7d3d.png)

after:
![image](https://user-images.githubusercontent.com/1632591/217258840-07519b12-3c4b-4ca4-8308-4ed21a692a49.png)

**Comment by sebescudie** [comment]
Ew, indeed, thanks. Will be fixed in upcoming version.
