### ISSUE TITLE
Selected version in dropdown is not refreshing when version has been uninstalled

### ISSUE THREAD

**Issue by chkworks** [sebescudie/GammaLauncher#47]

**Comment by sebescudie** [comment]
Thanks, will be fixed in upcoming.

**Comment by sebescudie** [comment]
Hey, thanks for the report. 

The available versions are indeed updated after the uninstall : the uninstalled version is not available anymore in the dropdown. Though, the current value of the dropdown is not being refreshed, so you still see the version you've just uninstalled, which is not cool. This is related to #44
