### ISSUE TITLE
Gammalauchner did not start 

### ISSUE THREAD

**Issue by phlegma** [sebescudie/GammaLauncher#5]
I often use the gammaLauncher and i want to add some functions like a kill button. Everything works out fine. Also the export builds the application. But when the Code is exported with the newest Gamma 2020.1. there is an [error ](https://gist.github.com/phlegma/8fa2801775263a9789ff269b9c382522)on startup.  Seems Elementa related. 
Same behavior with: 
gamma 2019.2.0.321

**Comment by phlegma** [comment]
Could be related to this fix: https://discourse.vvvv.org/t/2020-1-elementa-bang-broken/18354/4

**Comment by sebescudie** [comment]
Hey @phlegma, thanks for this suggestion. A new version of Elementa is on the way right now.  When it's released, I'm panning to add a few "quick access buttons", see #4 . A kill button be part of this update.

**Comment by phlegma** [comment]
@sebescudie i added this to #4 and close this issue.

**Comment by sebescudie** [comment]
sure, go for it!
