### ISSUE TITLE
Editable Packages opens VVVV folder

### ISSUE THREAD

**Issue by mhusinsky** [sebescudie/GammaLauncher#55]
A funny bug (or a feature I don't get):
As soon as I enter a package name into an "Editable Packages" field, the windows explorer will open a window with the current VVVV installation. is this intentional?

gamma launcher 5.1.0

**Comment by sebescudie** [comment]
Hey there, thanks for the feedback!

How weird, I cannot repro here :-)

Just added a package name and that was it. I'm in the middle of a project right now but I'll investigate that when I'm back home.
