### ISSUE TITLE
Disable repos temporarily

### ISSUE THREAD

**Issue by mhusinsky** [sebescudie/GammaLauncher#57]
in different development scenarios one might find himself needing different package repositories folders or editable packages.

right now those have to be removed not needed and later reentered when needed again.

how about adding some "enabled" checkboxes right next to the path/name to temporarily disable the respective entry temporarily? that would spare the tedious process of reentering the name/path.

![grafik](https://user-images.githubusercontent.com/3253299/233828125-8d4eab7b-dd4a-48ce-ae82-cef7f702727e.png)

**Comment by sebescudie** [comment]
Bonjour,

Yes, indeed :)

Will definitely add do that for the next release. Thanks for the suggestions!
