### ISSUE TITLE
Launcher doesn't show 5.0 stable

### ISSUE THREAD

**Issue by bj-rn** [sebescudie/GammaLauncher#58]
![image](https://user-images.githubusercontent.com/1632591/235140104-9ec03b55-09af-481b-98fb-dc345413c9d2.png)

![image](https://user-images.githubusercontent.com/1632591/235140238-71782503-0de0-4bc2-905e-8da73457ce2a.png)

**Comment by sebescudie** [comment]
Guess I'm only retrieving stuff from the `main` branch. This TeamCity API is a nightmare TBH. But thanks for the report, I'll have a look.

**Comment by bj-rn** [comment]
Didn't see this before: https://github.com/sebescudie/GammaLauncher/issues/32
