### ISSUE TITLE
Paths with spaces are not correctly handle: it does not open the correct VL file.

### ISSUE THREAD

**Issue by maximesouvestre** [sebescudie/GammaLauncher#60]
I'm dragging a VL file into GammaLauncher to open it.
Some of the paths to my file contains spaces, either in the folder name or in the filename. When that's the case, GammaLauncher starts VVVV but do not open the correct file. Instead, it creates a new blank one, wrongly named.

Here I have a folder called "A Dummy Folder":
![image](https://github.com/sebescudie/GammaLauncher/assets/50681359/7c56f868-d102-4132-83b1-e38fc93c2497)
When dragging my VL file into GammaLauncher, here's the result:
![image](https://github.com/sebescudie/GammaLauncher/assets/50681359/f27c65e5-aad5-421e-983e-7ea320f1cc9b)

Same with a path where spaces are contains in filename:
![image](https://github.com/sebescudie/GammaLauncher/assets/50681359/f268c74c-c45b-40ee-afaf-91460b3706b2)
![image](https://github.com/sebescudie/GammaLauncher/assets/50681359/fc704980-da62-414d-a326-e1f6c0f4abc1)

**Comment by sebescudie** [comment]
Eeew, thought that was fixed a while ago 😞 

Thanks for the update, will investigate that.

**Comment by maximesouvestre** [comment]
Thanks!

I also have to surround with quotes the path to set Nuget Override if it contains spaces.
I guess it is also related to the same issue.

![image](https://github.com/sebescudie/GammaLauncher/assets/50681359/5a16c7c5-a350-4959-a75c-b1b963ab6e01)
