### ISSUE TITLE
Display commandline options in tooltip

### ISSUE THREAD

**Issue by mhusinsky** [sebescudie/GammaLauncher#61]
i'd find it great to see the commandline-switch used for the tooltip of the checkbox options. it would be a nice (implicit) hint what this option actually does and one can look up the exact meaning in the gamma documentation/graybook

related forum thread: 
https://discourse.vvvv.org/t/how-to-use-different-gamma-different-nuggets-versions/21654/5

**Comment by sebescudie** [comment]
Hey!

Just remembered that hovering the checkboxes already shows a brief explanation of what the switch does. I'll add the corresponding command line switch though.

![image](https://github.com/sebescudie/GammaLauncher/assets/8690430/6544316f-6ccd-4db5-8b9b-677a47dbd738)
