### ISSUE TITLE
Make the launcher available via Winget

### ISSUE THREAD

**Issue by bj-rn** [sebescudie/GammaLauncher#66]
Just set up my new machine and for the first time used winget to install everything (that's available) via winget. I like. So would be nice if the launcher could be added.

**Comment by mhusinsky** [comment]
related to https://github.com/sebescudie/GammaLauncher/issues/12

**Comment by sebescudie** [comment]
Ahem, yes, this issue has been laying around since 2020 😬

I'll try to address this soon :)

**Comment by sebescudie** [comment]
This is apparently waiting for a validation but we're getting closer :)

https://github.com/microsoft/winget-pkgs/pull/122471

**Comment by sebescudie** [comment]
You can now `winget install GammaLauncher` :)
