### ISSUE TITLE
GammaLauncher has strange sorting after updating

### ISSUE THREAD

**Issue by berkut0** [sebescudie/GammaLauncher#70]
I can't say it's a serious problem, but I've had the wrong version installed a couple of times.

![image](https://github.com/sebescudie/GammaLauncher/assets/8849896/b7920de3-560a-43ae-a296-be386cc412e8)

**Comment by sebescudie** [comment]
Hey, thanks for the report. This is related to #64, and I think this happens when a build fails on the server. For some reason, when such a thing happens, previews are not ordered correctly.

**Comment by sebescudie** [comment]
One fix could be to sort releases by build date, which I'll do in the next release.

**Comment by sebescudie** [comment]
Releases dictionary is now cleared before each fetch attempt, let's see if that fixes it. Thanks again for the report!
