### ISSUE TITLE
Cleanup startup options toggles

### ISSUE THREAD

**Issue by sebescudie** [sebescudie/GammaLauncher#74]
Related to #69 

- [x] Update tooltip for `No Cache` : should rather say _Do not load any cached file from disk_
- [x] Get rid of _Disable Package Compiler_ and _Compile Source Packages_ toggles
- [x] Create a new _Show advanced startup options_ toggle in the settings, and only show _Debug_, _No Cache_ and _No Extensions_ if it is enabled

**Comment by chkworks** [comment]
May I ask, why "Disable Package Compiler" has been removed? You've been writing in the changelog, this was outdated, but I used it quite often to, well, to disable the package compiler. Is there now another way to do this?
Also, I would suggest to also flag "Use repos" as advanced.

Anyways, thank you very much for this christmas gift!
