### ISSUE TITLE
--editable-packages no longer seems to work with 5.2.1

### ISSUE THREAD

**Issue by bj-rn** [sebescudie/GammaLauncher#76]
Hey,

I am using the following settings:

![image](https://github.com/sebescudie/GammaLauncher/assets/1632591/4e0b5ab9-c003-463b-aeef-c66f623a5afd)
![image](https://github.com/sebescudie/GammaLauncher/assets/1632591/b3957d9a-82de-4c79-b369-cd4ba1ce2337)

The package is loaded from the repos folder but still I get this:
![image](https://github.com/sebescudie/GammaLauncher/assets/1632591/aeaccf62-f5f7-45dc-96fe-4b6af9cd7d98)

Re-Installed 5.2 and it works. It also works when using the command line arguments "manually".
Tried deleting the settings file and recreating the settings but makes no difference.

**Comment by sebescudie** [comment]
Ayayay, thanks for the feedback. Indeed, accidentally trashed this one while reworking startup args. Sorry for the inconvenience!
